- hosts: dbservers
  become: yes
  become_user: root

  vars:
    db:
      name: myappdb
      user: myappuser
      password: mysecretpassword

  pre_tasks:
    - name: Update APT package cache
      apt:
        update_cache: yes

    - name: Install PostgreSQL server, client, and contrib packages
      apt:
        name:
          - postgresql
          - postgresql-client
          - postgresql-contrib
        state: present

    - name: Install psycopg2 for Python via apt (Debian-safe)
      apt:
        name: python3-psycopg2
        state: present

    - name: Install pip3 (in case needed later)
      apt:
        name: python3-pip
        state: present

  tasks:
    - name: Ensure PostgreSQL service is running and enabled
      service:
        name: postgresql
        state: started
        enabled: yes

    - name: Create application database
      postgresql_db:
        state: present
        name: "{{ db.name }}"
      become_user: postgres

    - name: Create database user with password
      postgresql_user:
        state: present
        name: "{{ db.user }}"
        password: "{{ db.password }}"
      become_user: postgres

    - name: Grant all privileges on the database to the user
      postgresql_privs:
        type: database
        database: "{{ db.name }}"
        roles: "{{ db.user }}"
        grant_option: no
        privs: all
      become_user: postgres

    - name: Allow md5 connection for the db user in pg_hba.conf
      postgresql_pg_hba:
        dest: "/etc/postgresql/14/main/pg_hba.conf"
        contype: host
        databases: all
        users: "{{ db.user }}"
        address: 0.0.0.0/0
        method: md5
        create: true
      become_user: postgres
      notify: restart postgres

    - name: Allow PostgreSQL to listen on all IP addresses
      lineinfile:
        path: "/etc/postgresql/14/main/postgresql.conf"
        regexp: "^#?listen_addresses\\s*=.*"
        line: "listen_addresses = '*'"
      become_user: postgres
      notify: restart postgres

  handlers:
    - name: restart postgres
      service:
        name: postgresql
        state: restarted
